<?php

namespace Database\Seeders;

use App\Models\Subject;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $subject=[
            "Aboriginal Studies",
            "Abortion",
            "Accounting / Finance (general)",
            "Accounting: Corporate Finance",
            "Accounting: Economic History",
            "Accounting: Economic Theory",
            "Accounting: Economics",
            "Accounting: Intl. Economics",
            "Accounting: Intl. Finance",
            "Accounting: Money / Banking",
            "Accounting: Personal Finance",
            "Admissions Essays / Letters",
            "Advertising",
            "Aeronautics",
            "Africa / African Studies",
            "African-Americans (general)",
            "African-Americans: Civil Rights",
            "African-Americans: Historical",
            "African-Americans: Leaders",
            "African-Americans: Philosophy",
            "African-Americans: Politics",
            "African-Americans: Racism",
            "African-Americans: Social Issues",
            "African-Americans: Slavery",
            "Aging",
            "Agriculture",
            "American History",
            "American Indian Studies",
            "Anatomy",
            "Animals / Animal Rights",
            "Anthropology",
            "Aquaculture",
            "Archaeology",
            "Architecture",
            "Argumentative",
            "Art (general)",
            "Art: Ancient",
            "Art: Artists",
            "Art: Design",
            "Art: Famous Works",
            "Art: Genre",
            "Art: Graphic Arts",
            "Art: Photographic",
            "Art: Political Aspects",
            "Art: Social Aspects",
            "Asia / Asian Studies (general)",
            "Asia: China",
            "Asia: India",
            "Asia: Japan",
            "Asia: Korea",
            "Astronomy",
            "Authors",
            "Aviation",
            "Banking",
            "Biography",
            "Biology",
            "Birth Control",
            "Broadcasting",
            "Bureaucracy",
            "Business (general)",
            "Business: Advertising",
            "Business: Applied Operations",
            "Business: Plans",
            "Business: Theory",
            "Business: Case Studies",
            "Business: Companies",
            "Business: Consumer Behavior",
            "Business: Ethics",
            "Business: Human Resources",
            "Business: Industries",
            "Business: Information Systems",
            "Business: International",
            "Business: Law",
            "Business: Management",
            "Business: Management Theory",
            "Business: Marketing",
            "Business: Operations",
            "Business: Small",
            "Business: Technical Writing",
            "Canada / Canadian",
            "Capital Punishment",
            "Careers",
            "Caribbean",
            "Case Studies",
            "Chemistry",
            "Child Abuse",
            "Child Care",
            "Children",
            "China / Chinese",
            "Civil War",
            "Communication (general)",
            "Communication: Journalism",
            "Communication: Language",
            "Communication: Media",
            "Communication: Non-verbal",
            "Communication: Speech",
            "Communication: Television",
            "Communism",
            "Computer Science",
            "Computers (general)",
            "Computers: Industry",
            "Computers: Technology",
            "Computers: Connections",
            "Computers: Hardware",
            "Computers: History",
            "Computers: Internet",
            "Computers: Operating Systems",
            "Computers: Software",
            "Computers: Social Networking",
            "Computers: Wireless",
            "Construction",
            "Consumerism",
            "Cooking",
            "Corporal Punishment",
            "Corrections / Police (general)",
            "Corrections: Courts",
            "Corrections: Criminal Justice",
            "Corrections: Forensics",
            "Corrections: Intelligence",
            "Corrections: Juvenile Justice",
            "Corrections: Law Enforcement",
            "Corrections: Lawyers",
            "Corrections: Organized Crime",
            "Corrections: Police Misconduct",
            "Corrections: Prisons",
            "Corrections: Public Perception",
            "Corrections: Sentencing",
            "Cosmetology",
            "Counseling",
            "Creative Writing",
            "Criminal Justice (general)",
            "Criminal Justice: Juveniles",
            "Criminal Justice: Corrections",
            "Criminal Justice: Courts",
            "Criminal Justice: Police",
            "Criminal Justice: Prisons",
            "Criminal Justice: Intelligence",
            "Criminal Justice: Organized Crime",
            "Criminal Justice: Forensics",
            "Criminology",
            "Cuba",
            "Culture",
            "Death / Dying (general)",
            "Death: Euthanasia",
            "Death: Suicide",
            "Death: Elderly",
            "Death Penalty",
            "Disease",
            "Drama (general)",
            "Drama: American",
            "Drama: English",
            "Drama: World",
            "Drugs / Alcohol",
            "E-commerce",
            "Ecology",
            "Economics (general)",
            "Economics: Banking",
            "Economics: Economists",
            "Economics: Inflation",
            "Economics: International Trade",
            "Economics: Taxation",
            "Education (general)",
            "Education: Administration",
            "Education: Classroom Mgmt.",
            "Education: Coaching",
            "Education: Computers",
            "Education: Counseling",
            "Education: Countries",
            "Education: Curriculum",
            "Education: Foreign Countries",
            "Education: Higher Education",
            "Education: Homeschooling",
            "Education: Inclusion",
            "Education: Mainstreaming",
            "Education: Mathematics",
            "Education: Multiculturalism",
            "Education: Politics",
            "Education: Physical Education",
            "Education: Public vs. Private",
            "Education: Reading",
            "Education: Social Issues",
            "Education: Special Education",
            "Education: Teaching Methods",
            "Education: Technology",
            "Education: Theory",
            "Employment",
            "Energy",
            "Engineering",
            "English Literature",
            "Environmental Science",
            "Ethics / Morality",
            "Evolution",
            "Exercise",
            "Family / Marriage",
            "Feminism / Feminists",
            "Film",
            "Finance",
            "First Aid",
            "Foreign Relations",
            "Forensics",
            "France / French",
            "Gay / Lesbian (general)",
            "Gay: Adoption",
            "Gay: AIDS",
            "Gay: Civil Rights",
            "Gay: Discrimination",
            "Gay: Equality",
            "Gay: Homosexuality",
            "Gay: Marriage",
            "Gay: Raising Children",
            "Gay: Sex",
            "Gender / Sexuality",
            "Genetics",
            "Geography",
            "Germany / German",
            "Gerontology",
            "Global Politics (general)",
            "Global Politics: Comparative",
            "Global Politics: World Affairs",
            "Globalization",
            "Government (general)",
            "Government: Campaigns",
            "Government: Elections",
            "Government: Federal",
    "Government: Fiscal Policy",
    "Government: Foreign Policy",
    "Government: Agencies",
    "Government: Intl. Relations",
    "Government: Local",
    "Government: Military Agencies",
    "Government: Politicians",
    "Government: Presidents",
    "Government: Social Security",
    "Government: State",
    "Government: Theory",
    "Government: Welfare",
    "Graphics / Graphic Design",
    "Greek Studies",
    "Health (general)",
    "Health: Exercise",
    "Health: First Aid",
    "Health: Human Sexuality",
    "Health: Nursing",
    "Health: Nutrition",
    "Health: Public Health Issues",
    "Health: Safety",
    "Healthcare",
    "Higher Education",
    "History (general)",
    "History: Ancient",
    "History: Asian",
    "History: Civil War",
    "History: Colonial America",
    "History: European",
    "History: Great Britain",
    "History: Greek / Roman",
    "History: Holocaust Studies",
    "History: Israel",
    "History: Latin",
    "History: Middle East",
    "History: Pre-Colonial America",
    "History: Presidents",
    "History: Russia / USSR",
    "History: U.S. (after 1865)",
    "History: U.S. (before 1865)",
    "History: Wars (miscellaneous)",
    "History: World War I",
    "History: World War II",
    "Holocaust",
    "Homosexuality",
    "Housing",
    "Human Resources",
    "Human Rights",
    "Human Sexuality",
    "Immigration",
    "India / Indian",
    "Indonesia / Indonesian",
    "Information Technology",
    "International Relations",
    "Internet",
    "Japan / Japanese",
    "Jewish Studies",
    "Juvenile Delinquency / Crime",
    "Korea / Korean",
    "Labor / Union Studies",
    "Languages",
    "Latin America (general)",
    "Latin America: Caribbean",
    "Latin America: Brazil",
    "Latin America: Central America",
    "Latin America: Costa Rica",
    "Latin America: Cuba",
    "Latin America: Guatemala",
    "Latin America: Mexico",
    "Latin America: Puerto Rico",
    "Latin America: South America",
    "Law (general)",
    "Law: Business",
    "Law: Constitutional Law",
    "Law: Corrections",
    "Law: Courts",
    "Law: Enforcement",
    "Law: Historic Trials",
    "Law: International",
    "Law: Legal Briefs",
    "Law: Legal Issues",
    "Law: Litigation",
    "Law: Supreme Court",
    "Law: Theory",
    "Law: Trial System",
    "Leadership",
    "Learning",
    "Linguistics",
    "Literature (general)",
    "Literature: African",
    "Literature: African-American",
    "Literature: American",
    "Literature: Ancient",
    "Literature: Asian",
    "Literature: Authors",
    "Literature: British",
    "Literature: Canadian",
    "Literature: Caribbean",
    "Literature: Children's",
    "Literature: Classic (Greek/Roman)",
    "Literature: English",
    "Literature: French",
    "Literature: German",
    "Literature: Greek / Roman",
    "Literature: Irish / Scottish",
    "Literature: Italian",
    "Literature: Latin-American",
    "Literature: Medieval",
    "Literature: Portuguese",
    "Literature: Russian",
    "Literature: Shakespeare",
    "Literature: Spanish",
    "Literature: World",
    "Mainstreaming",
    "Management (general)",
    "Management: Motivation",
    "Management: Theory",
    "Marketing",
    "Mass Communications",
    "Mathematics",
    "Media",
    "Medical / Medicine (general)",
    "Medical: AIDS",
    "Medical: Alternative Medicine",
    "Medical: Cancer",
    "Medical: Dentistry",
    "Medical: Diseases",
    "Medical: Disorders",
    "Medical: Doctoring",
    "Medical: Epidemiology",
    "Medical: Ethics",
    "Medical: Health Care",
    "Medical: Holistic Medicine",
    "Medical: Issues",
    "Medical: Nursing",
    "Medical: Pharmacy",
    "Medical: Treatment",
    "Meteorology",
    "Mexico / Mexican-American",
    "Middle East",
    "Military",
    "Morality",
    "Motivation",
    "Multiculturalism",
    "Music",
    "Mythology (general)",
    "Mythology: Ancient Beliefs",
    "Mythology: Bible",
    "Mythology: Christianity",
    "Mythology: Church",
    "Mythology: Cults",
    "Mythology: Eastern",
    "Mythology: Greek / Roman",
    "Mythology: Islam",
    "Mythology: Judaism",
    "Mythology: Medieval",
    "Mythology: Native Indian",
    "Mythology: People",
    "Mythology: Political Issues",
    "Mythology: Religion",
    "Mythology: Superstition",
    "Mythology: Theology",
    "Mythology: World",
    "Native Americans",
    "Nature",
    "News",
    "Novels",
    "Nuclear Energy",
    "Nursing",
    "Nutrition",
    "Occult",
    "Oceanography",
    "Organized Crime",
    "Pakistan / Pakistani",
    "Paleontology",
    "Parapsychology",
    "Parenting",
    "Pharmacy",
    "Philosophy (general)",
    "Philosophy: Existence of God",
    "Philosophy: Famous Figures",
    "Philosophy: Free Will",
    "Philosophy: Greek",
    "Philosophy: Philosophers",
    "Philosophy: Religious",
    "Philosophy: Utopia",
    "Photography",
    "Physical Education (PE)",
    "Physics",
    "Physiology",
    "Planets",
    "Plays",
    "Poetry / Poets (general)",
    "Poetry / Poets: American",
    "Poetry / Poets: English",
    "Police",
    "Political Science / Politics (general)",
    "Politics: Campaigns",
    "Politics: Elections",
    "Politics: Federal",
    "Politics: Fiscal Policy",
    "Politics: Foreign Policy",
    "Politics: Government Agencies",
    "Politics: International Relations",
    "Politics: Local",
    "Politics: Military Agencies",
    "Politics: Politicians",
    "Politics: Presidential Studies",
    "Politics: Social Security",
    "Politics: State",
    "Politics: Theory",
    "Politics: Voting",
    "Politics: Welfare",
    "Pollution",
    "Population",
    "Pornography",
    "Privacy",
    "Pros and Cons",
    "Programming",
    "Psychiatry",
    "Psychology (general)",
    "Psychology: Abnormal",
    "Psychology: Adolescent",
    "Psychology: Behaviorism",
    "Psychology: Child",
    "Psychology: Cognitive",
    "Psychology: Counseling",
    "Psychology: Developmental",
    "Psychology: Disorders",
    "Psychology: Dreams",
    "Psychology: Experimental",
    "Psychology: Freud",
    "Psychology: History",
    "Psychology: Jung",
    "Psychology: Parapsychology",
    "Psychology: Personality",
    "Psychology: Physiology",
    "Psychology: Piaget",
    "Psychology: Psychotherapy",
    "Psychology: Rogers",
    "Psychology: Social",
    "Psychology: Testing",
    "Psychology: Theories",
    "Psychology: Therapy",
    "Public Administration",
    "Public Relations",
    "Race / Racism",
    "Reading",
    "Real Estate",
    "Recreation / Leisure",
    "Religion (general)",
    "Religion: Bible",
    "Religion: Buddhism",
    "Religion: Christianity",
    "Religion: Church vs. State",
    "Religion: Cults",
    "Religion: Eastern",
    "Religion: Famous People",
    "Religion: Hinduism",
    "Religion: Islam",
    "Religion: Janism",
    "Religion: Judaism",
    "Religion: Koran",
    "Religion: Political Issues",
    "Religion: Shinto",
    "Religion: Superstition",
    "Religion: Taoism",
    "Religion: Theology",
    "Religion: Tora",
    "Religion: World",
    "Roman Studies",
    "Russia / Russian",
    "Safety",
    "School Issues",
    "Science",
    "Security",
    "Shakespeare",
    "Slavery",
    "Social Media",
    "Sociology (general)",
    "Sociology: Counseling",
    "Sociology: Family Issues",
    "Sociology: Human Services",
    "Sociology: Politics",
    "Sociology: Problems",
    "Sociology: Race",
    "Sociology: Research",
    "Sociology: Services",
    "Sociology: Sex / Aids",
    "Sociology: Social Work",
    "Sociology: Theories",
    "Sociology: Theorists",
    "Sociology: Therapy",
    "Sociology: Utopian Societies",
    "Sociology: Welfare",
    "Software",
    "Soviet Union / USSR",
    "Speech",
    "Sports (general)",
    "Sports: Advertising",
    "Sports: Athletic Fitness",
    "Sports: Business",
    "Sports: Coaching",
    "Sports: College",
    "Sports: Culture",
    "Sports: Drugs",
    "Sports: Economics",
    "Sports: Gambling",
    "Sports: High School",
    "Sports: Law",
    "Sports: Management",
    "Sports: Medicine",
    "Sports: Olympics",
    "Sports: Political Issues",
    "Sports: Professional Athletes",
    "Sports: Recreational",
    "Sports: Social Issues",
    "Sports: Steroids",
    "Sports: Teams",
    "Sports: Violence",
    "Sports: Women",
    "Sports: Youth",
    "Teaching (general)",
    "Teaching: Administration",
    "Teaching: Classroom Mgmt.",
    "Teaching: Coaching",
    "Teaching: Computers",
    "Teaching: Counseling",
    "Teaching: Countries",
    "Teaching: Curriculum",
    "Teaching: ESL",
    "Teaching: Foreign Countries",
    "Teaching: Higher Education",
    "Teaching: Homeschooling",
    "Teaching: Inclusion",
    "Teaching: Mathematics",
    "Teaching: Politics",
    "Teaching: Physical Education",
    "Teaching: Public vs. Private",
    "Teaching: Reading",
    "Teaching: Social Issues",
    "Teaching: Special Education",
    "Teaching: Teaching Methods",
    "Teaching: Technology",
    "Teaching: Theory",
    "Technical Writing",
    "Technology",
    "Television",
    "Terrorism",
    "Theology",
    "Theory",
    "Therapy",
    "Topography",
    "Tourism",
    "Transportation (general)",
    "Transportation: Aviation",
    "Transportation: Boat",
    "Transportation: Bus",
    "Transportation: Car",
    "Transportation: Environment",
    "Transportation: Freight",
    "Transportation: Public",
    "Transportation: Railroads",
    "Transportation: SUV",
    "Urban Studies",
    "Vietnam",
    "Violence",
    "War",
    "Weather",
    "Western Civilization (general)",
    "Western Civ: Ancient Civilizations",
    "Western Civ: England (pre-1800)",
    "Western Civ: Europe's Culture",
    "Western Civ: Europe's History",
    "Western Civ: France (pre-1800)",
    "Western Civ: Greeks / Greece",
    "Western Civ: Romans / Italy",
    "Witchcraft / Magic / Voodoo",
    "Women (general)",
    "Women: Abortion",
    "Women: Achievements",
    "Women: Activists",
    "Women: Birth Control",
    "Women: Civil Rights",
    "Women: Cultures",
    "Women: Employment",
    "Women: Feminism / Feminists",
    "Women: Foreign Countries",
    "Women: Gender / Society",
    "Women: Health Issues",
    "Women: Sexuality",
    "Women: Social Issues",
    "Women: Workforce",
    "World Literature",
    "Writing",
    "Zoology",
    "Other (not listed above)",
        ];

        foreach( $subject as $s){
            $sub=Subject::create([
                'title'=>$s
            ]);
        }
    }
}
